{{- if .Values.mysql.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: "mysql:8.0"
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.password | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.database | quote }}
          ports:
            - containerPort: {{ .Values.mysql.port }}
              name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mysql
  labels:
    app: mysql
spec:
  ports:
    - port: {{ .Values.mysql.port }}
      targetPort: mysql
  selector:
    app: mysql
{{- end }}
