apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Values.serviceName }}-{{ .Values.color | default "blue" }}-deployment"
  labels:
    app: "{{ .Values.serviceName }}"
    color: "{{ .Values.color | default "blue" }}"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "{{ .Values.serviceName }}"
      color: "{{ .Values.color | default "blue" }}"
  template:
    metadata:
      annotations:
        rollout/run: {{ randAlphaNum 5 | quote }}
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "{{ .Values.service.port }}"
      labels:
        app: "{{ .Values.serviceName }}"
        color: "{{ .Values.color | default "blue" }}"
    spec:
      containers:
        - name: "{{ .Values.serviceName }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: "global-infrastructure-config"
            - configMapRef:
                name: "{{ .Values.serviceName }}-config"
          env:
            - name: SERVER_PORT
              value: "{{ .Values.service.port }}"
{{- if ne .Values.serviceName "discovery-server" }}
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "$(EUREKA_SERVER_URL)"
{{- end }}
            - name: MANAGEMENT_OTLP_TRACING_ENDPOINT
              value: "$(JAEGER_OTLP_ENDPOINT)"
            - name: MANAGEMENT_TRACING_SAMPLING_PROBABILITY
              value: "$(OTEL_SAMPLING_PROBABILITY)"
            - name: MANAGEMENT_TRACING_PROPAGATION_TYPE
              value: "W3C"
            - name: LOGGING_LEVEL_ROOT
              value: "$(LOGGING_LEVEL_ROOT)"
            - name: LOGGING_LEVEL_ORG_HIBERNATE_SQL
              value: "$(LOGGING_LEVEL_ORG_HIBERNATE_SQL)"
            - name: LOGGING_LEVEL_COM_EXAMPLE
              value: "$(LOGGING_LEVEL_COM_EXAMPLE)"
            - name: MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE
              value: "$(MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE)"
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
