{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.serviceName }}-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: {{ default (printf "/%s(/|$)(.*)" .Values.serviceName) .Values.ingress.path }}
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.serviceName }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
