server:
    port: 8080

spring:
    application:
        name: api-gateway
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
            routes:
                - id: auth-service
                  uri: lb://auth-service
                  predicates:
                      - Path=/api/v1/auth/**
                - id: employee-service
                  uri: lb://employee-service
                  predicates:
                      - Path=/api/v1/employees/**
                  filters:
                      - AuthenticationFilter
                - id: account-service
                  uri: lb://account-service
                  predicates:
                      - Path=/api/v1/accounts/**
                  filters:
                      - AuthenticationFilter
                - id: customer-service
                  uri: lb://customer-service
                  predicates:
                      - Path=/api/v1/customers/**
                  filters:
                      - AuthenticationFilter
                - id: transaction-service
                  uri: lb://transaction-service
                  predicates:
                      - Path=/api/v1/transactions/**
                  filters:
                      - AuthenticationFilter
                - id: notification-service
                  uri: lb://notification-service
                  predicates:
                      - Path=/api/v1/notifications/**
                  filters:
                      - AuthenticationFilter
                - id: payment-service
                  uri: lb://payment-service
                  predicates:
                      - Path=/api/v1/payments/**
                  filters:
                      - AuthenticationFilter
                - id: kafka-sample
                  uri: lb://payment-service
                  predicates:
                      - Path=/api/v1/kafka-sample/**
                  filters:
                      - AuthenticationFilter
                - id: common-service
                  uri: lb://common-service
                  predicates:
                      - Path=/api/common/**
                  filters:
                      - AuthenticationFilter

eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://discovery-server.backend.svc.cluster.local:8761/eureka/}

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            probes:
                enabled: true
            show-details: always
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
    tracing:
        sampling:
            probability: 1.0
    otlp:
        tracing:
            endpoint: http://jaeger.monitoring.svc.cluster.local:4318/v1/traces

jwt:
    secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
