{
 "title": "Kafka + Notification Pipeline",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Kafka Topics Available",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "count(kafka_topic_partitions)", "legendFormat": "Topics" }
   ]
  },
  {
   "title": "Kafka Consumer Groups",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "count(kafka_consumergroup_members)",
     "legendFormat": "Groups"
    }
   ]
  },
  {
   "title": "Consumer Lag (notification-group)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=\"notification-group\"})",
     "legendFormat": "Lag"
    }
   ]
  },
  {
   "title": "Total Kafka Messages In Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mps" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset[1m]))",
     "legendFormat": "msg/s"
    }
   ]
  },
  {
   "title": "Messages per Topic (payment.created, account.created, transaction.created)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_topic_partition_current_offset{topic=~\"payment.created|account.created|transaction.created\"}",
     "legendFormat": "{{topic}} partition={{partition}}"
    }
   ]
  },
  {
   "title": "Consumer Lag Over Time (notification-group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{consumergroup=\"notification-group\"}",
     "legendFormat": "{{topic}} lag"
    }
   ]
  },
  {
   "title": "Payment Service Kafka Events Published",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(kafka_topic_partition_current_offset{topic=\"payment.created\"}[1m])",
     "legendFormat": "payment events/s"
    }
   ]
  },
  {
   "title": "Notification Service — Kafka Messages Consumed Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{service=\"notification-service\", uri=\"/api/v1/notifications\"}[1m])",
     "legendFormat": "notifications saved/s"
    }
   ]
  },
  {
   "title": "Kafka Broker Availability",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "up{job=\"kafka-exporter\"}",
     "legendFormat": "Kafka Broker"
    }
   ]
  }
 ]
}