apiVersion: v1
kind: ConfigMap
metadata:
  name: global-infrastructure-config
  namespace: backend
data:
  EUREKA_SERVER_URL: "http://discovery-server.backend.svc.cluster.local:8761/eureka"
  KAFKA_BOOTSTRAP_SERVERS: "kafka.external-tools.svc.cluster.local:9092"
  MYSQL_HOST: "mysql.db.svc.cluster.local"
  POSTGRES_HOST: "springbootapp-db-postgres.db.svc.cluster.local"
  DB2_HOST: "db2.db.svc.cluster.local"
  DB2_PORT: "50000"
