serviceName: "notification-service"
image:
  repository: "docker.io/rameshkp2/notification-service"
  pullPolicy: Always
  tag: "784ca8a0e690"
service:
  type: ClusterIP
  port: 8084
appConfig:
  KAFKA_LISTENER_ENABLED: "true"
