apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: banking-platform
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: db
  source:
    repoURL: https://github.com/prameshmca5/spring-docker-kuber-cicd.git
    targetRevision: cicd-docker-k8s-helm-argocd
    path: gitops/db/kafka
  destination:
    server: https://kubernetes.default.svc
    namespace: external-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
