apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - db-storage.yaml
  - db-mysql-shared.yaml
  - db-auth-postgres.yaml
  - mysql-account.yaml
  - postgres-customer.yaml
  - mysql-transaction.yaml
  - mysql-common.yaml
  - mysql-notification.yaml
  - mysql-payment.yaml
  - mysql-card.yaml
  - mysql-loan.yaml
  - postgres-employee.yaml
