apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - backend-shared.yaml
  - discovery-server.yaml
  - api-gateway.yaml
  - account-service.yaml
  - customer-service.yaml
  - transaction-service.yaml
  - notification-service.yaml
  - payment-service.yaml
  - card-service.yaml
  - loan-service.yaml
  - employee-service.yaml
  - common-service.yaml
  - auth-service.yaml
