apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payment-service
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: banking-platform
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: backend
  source:
    repoURL: https://github.com/prameshmca5/spring-docker-kuber-cicd.git
    targetRevision: cicd-docker-k8s-helm-argocd
    path: helm-charts/banking-service
    helm:
      releaseName: payment-service
      valueFiles:
        - values-payment-service.yaml
        - ../environments/dev/payment-service.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
