server:
    port: 8761

spring:
    application:
        name: discovery-server

eureka:
    instance:
        hostname: localhost
    client:
        enabled: true
        register-with-eureka: false
        fetch-registry: false
        service-url:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
    endpoints:
        web:
            exposure:
                include: "*"
    endpoint:
        health:
            probes:
                enabled: true
            show-details: always
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
