apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-backend-shared
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/prameshmca5/spring-docker-kuber-cicd.git
    targetRevision: HEAD
    path: gitops/backend-shared
  destination:
    server: https://kubernetes.default.svc
    namespace: backend
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
