apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: banking-backend-services
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  generators:
    - list:
        elements:
          - service: discovery-server
            port: 8761
          - service: api-gateway
            port: 8080
          - service: account-service
            port: 8080
          - service: customer-service
            port: 8080
          - service: transaction-service
            port: 8080
          - service: notification-service
            port: 8080
          - service: payment-service
            port: 8080
          - service: employee-service
            port: 8080
          - service: common-service
            port: 8080
          - service: auth-service
            port: 8080
  template:
    metadata:
      name: "{{service}}"
      labels:
        app.kubernetes.io/part-of: banking-platform
    spec:
      project: default
      source:
        repoURL: https://github.com/prameshmca5/spring-docker-kuber-cicd.git
        targetRevision: cicd-docker-k8s-helm-argocd
        path: helm-charts/banking-service
        helm:
          releaseName: "{{service}}"
          values: |
            serviceName: "{{service}}"
            service:
              port: {{port}}
            image:
              repository: "springbootapps-{{service}}"
              pullPolicy: IfNotPresent
              tag: "latest"
            ingress:
              enabled: true
              host: "qactsai.local"
            activeColor: "blue"
            color: "blue"
            createService: true
      destination:
        server: https://kubernetes.default.svc
        namespace: backend
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true