apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: banking-monitoring
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://github.com/prameshmca5/spring-docker-kuber-cicd.git
    targetRevision: cicd-docker-k8s-helm-argocd
    path: helm-charts/monitoring-stack
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true