name: Build and Deploy to Local Kubernetes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Start Minikube
        uses: medyagh/setup-minikube@master

      - name: Build Docker Images
        run: |
          eval $(minikube docker-env)
          chmod +x ./build-images.sh
          ./build-images.sh

      - name: Deploy to Minikube
        run: |
          chmod +x ./deploy-all.sh
          ./deploy-all.sh

      - name: Verify Deployment
        run: |
          kubectl get pods -A
          kubectl get svc -A
